name: Deploy Backend

on:
  push:
    branches: ["main"]
    paths: ["backend/**"]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'gdpr-backend'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  NODE_VERSION: '22.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # checkout repository so workflow has acces

    - name: Setup Node
      uses: actions/setup-node@v4 # add NODE.js
      with:
        node-version: ${{ env.NODE_VERSION }} ## podaj wersje NODE.js

    - name: Install dependencies
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm ci
      ## wybierz plik
      ## install dependencies
    - name: Build
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm run build --if-present
      ## wybierz plik
      ## szuki plik build i wykonuje go?


    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}