name: cicd #a
on: 
  push:
    branches: ["main"]
permissions: # dodalem ten kod bo bez niego wyrzuca
  contents: read   
  pages: write      
  id-token: write
jobs:
    deploy:
      name: Lint code base
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Pages
          uses: actions/configure-pages@v4

        - name: Upload artifact
          uses: actions/upload-pages-artifact@v3
          with:
             path: '.' # Ścieżka do plików strony

        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4
