name: Deploy Frontend
on: 
  push:
    branches: ["main"]
    paths: ["frontend/**"]  #  trigger in case frontend changed


concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # checkout repository so workflow has acces

      - name: Setup Pages
        uses: actions/configure-pages@v4 #extract metadata and domena

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # before deploy to github pages use this.
        with:
          path: 'frontend' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # nazwa mówi za siebie
