name: Deploy to Github Pages
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      # 1. NAJPIERW POBIERAMY KOD
      - name: Checkout
        uses: actions/checkout@v4

      # 2. POTEM USTAWIAMY NODE.JS
      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Używamy nowszej wersji, 12 jest już przestarzała

      # 3. INSTALUJEMY I BUDUJEMY W FOLDERZE FRONTEND
      - name: Install and Build
        working-directory: frontend 
        run: |
          npm ci
          npm run build

      # 4. WYSYŁAMY NA STRONĘ
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build
          branch: gh-pages